### ISSUE TITLE
Original title doesn't show mouse-over text

### ISSUE THREAD

**Issue by AronHK** [ajayyy/DeArrow#102]
Hovering over a title shows it as mouse-over text, which is useful when the title is too long to fit normally.
![Screenshot 2023-07-15 17-32-59](https://github.com/ajayyy/DeArrow/assets/9072794/2d166c8b-e3ed-4463-83c9-6337ac989e6b)

However the same thing doesn't work when a video has a user submitted title and I'm viewing the original.
![Screenshot 2023-07-15 17-33-29](https://github.com/ajayyy/DeArrow/assets/9072794/1ac0f1d0-f8c6-41dc-bc1d-394444c66e30)

**Comment by ajayyy** [comment]
Which place, they put the title text on different elements in different places in the ui

**Comment by AronHK** [comment]
The home/subscriptions page.
