### ISSUE TITLE
Punctuation issue with Yu-Gi-Oh!

### ISSUE THREAD

**Issue by Mrfiregem** [ajayyy/DeArrow#107]
I was wondering if there's some sort of global whitelist that you can add `Yu-Gi-Oh!` to, so that it doesn't get converted to `Yu-Gi-Oh.` This wasn't the case before, but something must've changed such that the punctuation is (incorrectly) edited automatically now.

**Comment by ajayyy** [comment]
Added, if you want to help, you can ask for google sheets link via discord or matrix
