### ISSUE TITLE
Video title formatter shouldn't capitalize (or lowercase) Greek letters

### ISSUE THREAD

**Issue by nrgill28** [ajayyy/DeArrow#111]
Original title for video
![Screenshot_20230723_024253](https://github.com/ajayyy/DeArrow/assets/22647801/8d4c1b9c-d05b-4fc6-a133-0eb192eab18c)

vs. formatted title
![Screenshot_20230723_024249](https://github.com/ajayyy/DeArrow/assets/22647801/37ff922f-6ac5-4a5d-bf8a-a8b0e9f450d3)

The character for pi `π` is getting turned into its capitalized form `Π`, which for math related stuff is not ideal.

**Comment by ajayyy** [comment]
I wonder if there is a Unicode range for these symbols
