### ISSUE TITLE
A Turkish letter "İ" looks creepy. With replace title option.

### ISSUE THREAD

**Issue by sertchan** [ajayyy/DeArrow#118]
It looks like this.
![image](https://github.com/ajayyy/DeArrow/assets/53477192/e26646d9-02cb-464a-91d4-39daed029167)

While it should looks like this.
![image](https://github.com/ajayyy/DeArrow/assets/53477192/a5395d28-a2e7-42f1-978f-4d028f41bfa8)

Turkish has a capital letter 'İ' which is not present in English, and when reformatting the titles with this extension, it strangely converts this letter to a 'i̇' instead of 'i'. It looks kinda weird.

**Comment by ajayyy** [comment]
This is the behavior of the toLowerCase function in the browser.

It converts it into an i character followed by a "COMBINING DOT ABOVE" unicode modifier

`i\u307`
`i``̇`
which becomes `i̇`


I wonder if there is a special reason for that, or just an issue with the standard

**Comment by sertchan** [comment]
I thought "If its related to browser (which i use Firefox) changing browser could solve the problem temporary".
Then i tried with chromium.
![image](https://github.com/ajayyy/DeArrow/assets/53477192/52ec6840-c284-44fe-874e-e2693207a236)
![image](https://github.com/ajayyy/DeArrow/assets/53477192/51e28383-6083-4515-8d7f-63f2ba8d6cc1)
It seems pretty well.

Thus, I can say its a bug related to Firefox's toLowerCase function. That's all i know.

**Comment by sertchan** [comment]
Also in Turkish we've capital "ı" in turkish titles it looks like:
![image](https://github.com/ajayyy/DeArrow/assets/53477192/45677e0c-c9bf-41fd-ac9f-cb7fab04e8ef)
Same as I in english but it's a different letter so with extension the title should be:
Asla Oynamam Dediğim Oyun Beni Şaşırttı! / Bu oyunu beklediğim için aşşağılandım!
Not:
![image](https://github.com/ajayyy/DeArrow/assets/53477192/d58dd7b3-57d0-4c24-b670-a6cd9b792da0)

I don't know there is possible to perceiving language and presenting different letters accordingly?
