### ISSUE TITLE
'Title Case' title format does not fully capitalise acronyms

### ISSUE THREAD

**Issue by Reeceeboii** [ajayyy/DeArrow#120]
For example, applying Title Case on a title that contains the string `"ai"` will result in `"Ai"` rather than `"AI"`.
There should be a list of special cases for common acronyms (or another similar implementation) to avoid incorrectly capitalised acronyms.

Example below.

Original:
![Screenshot 2023-08-01 134917](https://github.com/ajayyy/DeArrow/assets/42159320/66d75829-c27d-47f4-b078-9ab0a62a4630)

'Title Case' applied:
![Screenshot 2023-08-01 134936](https://github.com/ajayyy/DeArrow/assets/42159320/505e680b-42f2-4ff1-9ba7-e9025ad559c9)

**Comment by ajayyy** [comment]
Right now, we allow any already capitalized words 3 letters or less, and have a whitelist for the larger ones. This reduces the number that we need to keep track of.

For some reason they didn't capitalize it in the original here though 

I think maintaining a list for smaller acronyms like this would be a lot of work and probably not worth it

**Comment by ajayyy** [comment]
The edge case of them capitalizing it wrong probably isn't that common

**Comment by Reeceeboii** [comment]
> Right now, we allow any already capitalized words 3 letters or less, and have a whitelist for the larger ones. This reduces the number that we need to keep track of.
> 
> For some reason they didn't capitalize it in the original here though
> 
> I think maintaining a list for smaller acronyms like this would be a lot of work and probably not worth it

Okay that's fine, ty for reply. Happy for this to be closed unless you want it open for whatever reason :)
