### ISSUE TITLE
Use transparent backgrounds on thumbnails instead of grey

### ISSUE THREAD

**Issue by sertchan** [ajayyy/DeArrow#121]
For example:
![image](https://github.com/ajayyy/DeArrow/assets/53477192/659d89c4-9270-4d34-b811-6905a9c52084)

It would have been more appealing to the eye if it had looked like this:
![yoyoo](https://github.com/ajayyy/DeArrow/assets/53477192/a2416446-c164-4ce1-bda3-ebace28ba278)

I think the same thing can be easily replicated within a white theme. I'm curious to hear your opinions; I believe its current appearance is quite distracting on the homepage.

**Comment by ajayyy** [comment]
This seems to happen only on the homepage

**Comment by sertchan** [comment]
It's more like a bug then?

**Comment by ajayyy** [comment]
Looked into this but am not able to figure out which part of the css controls this color

**Comment by ajayyy** [comment]
Was able to find it

**Comment by sertchan** [comment]
Looks Good To Me!
