### ISSUE TITLE
Why is it removed from the Firefox addon place?

### ISSUE THREAD

**Issue by MrGoatsy** [ajayyy/DeArrow#122]
Why did it get removed?

**Comment by ajayyy** [comment]
The Mozilla reviewer spotted an XSS vulnerability in the code and took it down. I have fixed the bug in https://github.com/ajayyy/DeArrow/releases/tag/1.2.6 and now it will have to wait for them to review it.

The good news is that no one has abused this, and there is a server-side mitigation to make it so it can't be abused even on older extension versions.
