### ISSUE TITLE
Firefox Extension page is down

### ISSUE THREAD

**Issue by Grooty12** [ajayyy/DeArrow#123]
When I visit the Dearrow Firefox Addon page ([here](https://addons.mozilla.org/en-US/firefox/addon/dearrow/)), I get an error:
![Screenshot_20230805_110907](https://github.com/ajayyy/DeArrow/assets/85930101/bf7ab76a-dbbc-44e5-a4f4-b383d09b3fcb)

**Comment by ajayyy** [comment]
#122

**Comment by ajayyy** [comment]
![Screenshot_20230809-085951](https://github.com/ajayyy/DeArrow/assets/12688112/5da5b151-9edd-4757-859f-d70b8b2c60cc)
