### ISSUE TITLE
DeArrow's been unlisted from the Firefox Addon Store

### ISSUE THREAD

**Issue by crystallikelaw** [ajayyy/DeArrow#126]
Don't know if it was deliberate, but thought I'd post an issue in case you weren't aware.

Link from this repo's readme:
https://addons.mozilla.org/en-US/firefox/addon/dearrow/

Firefox doesn't allow unsigned addons unless you install Dev or Nightly.

**Comment by ajayyy** [comment]
![Screenshot_20230809-085951](https://github.com/ajayyy/DeArrow/assets/12688112/d086f518-d0ff-4cc4-b5ad-bf0eaa106580)
