### ISSUE TITLE
Edit button doesn't show up on certain videos

### ISSUE THREAD

**Issue by aaronliu0130** [ajayyy/DeArrow#129]
For example, https://www.youtube.com/watch?v=_qUqHehEW4k . Tested on Waterfox on Windows and Linux.

**Comment by ajayyy** [comment]
Waterfox is not fully supported

**Comment by aaronliu0130** [comment]
Huh. It should be the same as Firefox, and the edit button does show up on most other videos such as Tom Scott's.

**Comment by ajayyy** [comment]
I cannot reproduce this

**Comment by aaronliu0130** [comment]
Hmm, I can't reproduce it anymore either.
