### ISSUE TITLE
Custom words to exempt from title formatting

### ISSUE THREAD

**Issue by evscye** [ajayyy/DeArrow#130]
Title says it all. The number one flaw, out of the few there is, for me is the lack of acronyms in the block list or the ability to add words/acronyms etc to a title format blocklist.

**Comment by ajayyy** [comment]
There's a Google sheets you can contribute to if you ask on matrix/discord

**Comment by evscye** [comment]
Great, will do

**Comment by ajayyy** [comment]
duplicate #105
