### ISSUE TITLE
bug: title remain from the previous video.

### ISSUE THREAD

**Issue by kishanhitk** [ajayyy/DeArrow#132]
![image](https://github.com/ajayyy/DeArrow/assets/41117038/c4a17fa2-35c6-43c2-9592-1c65546e64f8)
While watching MKBHD's "Samsung Galaxy Tab S9 Ultra Review" on YouTube, I switched to this video titled "What the Heck Is the Event Loop Anyway? | Philip Roberts | JSConf EU". However, the title displayed did not update and still showed the title of the previous video.

**Comment by ajayyy** [comment]
60c5f9982cd6881e07fc9d90a654778cf04d043e
