### ISSUE TITLE
Reset settings when the addon doesn't run properly? (Firefox Dev. edition)

### ISSUE THREAD

**Issue by anijatsu** [ajayyy/DeArrow#135]
Hi,
I might have a curious problem, since it seems like the addon's settings storage could've been corrupted to the point where the addon icon doesn't open up anything:
<img width="439" alt="Screenshot 2023-08-20 at 05 14 23" src="https://github.com/ajayyy/DeArrow/assets/1882015/b7fbb999-b46b-4adf-a1af-5bc5527faacf">
(the thin line is the empty iframe/box that I get when clicking on the addon's toolbar icon)

and the preferences page only contains the tab names, w/o any actual options:
<img width="1060" alt="Screenshot 2023-08-20 at 05 11 32" src="https://github.com/ajayyy/DeArrow/assets/1882015/b073d0bc-d40d-4335-a650-87d034795253">

How can I go about resetting the addon's settings storage when using Firefox Developer Edition? I'm currently on 117.0b9, but this has been happening for the past 2 weeks, making me disable the addon thinking it's just been a temporary bug.

**Comment by ajayyy** [comment]
Check about:config and look for webextension sync. Do you have it disabled?

**Comment by anijatsu** [comment]
It was on/true. What can be my next steps after toggling it?
Also searching for 'dearrow' in the same page there's one result - boolean property, set as true:
"extensions.webextensions.ExtensionStorageIDB.migrated.deArrow@ajay.app"
Searching for UUID that appears when opening Dearrow's preferences page ("90e09795-a84b-4934-a19c-ee3b5580cedc") does not bring any results.

**Comment by ajayyy** [comment]
If you uninstall it and reinstall it should clearq your settings

**Comment by ajayyy** [comment]
And don't turn that setting off. It should be on. The sync web extensions setting
