### ISSUE TITLE
Be more transparent about possible, future soft-paywalling the add-on

### ISSUE THREAD

**Issue by Andre601** [ajayyy/DeArrow#136]
As of right now, the only notice about the add-on possibly receiving a soft paywall for new users is a very small text you often will overlook because of the large add-on icons above.

![grafik](https://github.com/ajayyy/DeArrow/assets/11576465/3f584da6-c59d-405f-be65-bd0f048ba945)

Given your statement that you - ajayyy - want to be "as open as possible" is this almost ironic to have as this is the oposite of being transparent and open.
It feels like all those fine-prints companies have to wiggle themself out of any trouble.

So, it would be better imo to make it clear and obvious that there will be some kind of paywall in the future. And maybe also state what possible things would be behind it, so people are prepared for when this would happen (if it would happen).

**Comment by ajayyy** [comment]
I merged your or to make the text bigger. I'll be enabling the paywall later today or tomorrow

You can see what the payment page will look like here: https://DeArrow.ajay.app/payment
