### ISSUE TITLE
Free access button is gone on safari

### ISSUE THREAD

**Issue by cootshk** [ajayyy/DeArrow#143]
I've tried building SafariExtension.zip and ChromeExtension.zip for safari, both have the request free access button missing (MacOS, MacBook Air 2022 with M1 chip)

**Comment by ajayyy** [comment]
Do you have js disabled?

**Comment by cootshk** [comment]
I don't think so

Everything else works, including the side-by-side with mouse movement. I was eventually able to dig into the js source to send an API request

**Comment by ajayyy** [comment]
Actually, I just remembered that Safari will not work properly with this paid-access system since I didn't it uses APIs not available in Safari (and I did not port it since it's not needed in the app store version). If you send me an email, I can explain how to force it to be activated.
