### ISSUE TITLE
Don't replace title if it is only formatted differently when title formatting disabled

### ISSUE THREAD

**Issue by MrJPGames** [ajayyy/DeArrow#145]
The issue is easiest explained through this example: https://www.youtube.com/watch?v=5cwdhuWqY0Q
The original title of that video is: "Two Grant Imahara Stories"
DeArrow user submitted version: "Two grant imahara stories" (ignoring the fact the name is incorrectly not capitalized here).

The problem is that the submitted title in this example should never be used. For users that prefer this title format the "First letter upercase" "Title Format" setting should be used instead. For other users (such as myself) that dislike this formatting it should not be imposed because someone erroneously submitted their personal formatting preference.

I'd suggest that locally the current DeArrow title is compared to the current official title. If any of the "Title Format" options result in the DeArrow title it should be ignored, and the original title + the user's selected formatting should be used instead. Alternatively you might want to implement a check for alternative titles and find the best rated one that is not the original title formatted differently, and use that instead, if possible and only if not fallback to the original.

EDIT: This should likely also check for emoji removal etc. In other words any time it's relatively easy to check if a user submission could've been created using a built-in DeArrow setting that title should be rejected. Users preferring that style should use the setting and submissions should only be used in cases where the content not the style of the title has to change.

**Comment by ajayyy** [comment]
If there is a format selected, then we do want to allow this as the use-case is correcting issues with the title-formatter and making sure it knows which words are proper nouns.

But, if title formatting is disabled, then it probably should be ignored.

**Comment by MrJPGames** [comment]
Title formatting is disabled in my settings.

What the issue is about is users submitting the original title with different formatting only. I'd prefer if these submissions are not applied as it makes the titles more inconsistent and I fail to see the value as the user who submitted that title could change the user on their end instead.
