### ISSUE TITLE
lowercase, first letter uppercase, capitalize words shouldn't respect >

### ISSUE THREAD

**Issue by SuperStormer** [ajayyy/DeArrow#150]
I assumed that the point of the lowercase option was for all titles to be lowercased, but this assumption is broken if a title uses > to force capitalization (eg. a proper noun to make sentence case work).
https://discord.com/channels/603643120093233162/897699762738966558/1155099888929996933

Similar reasoning for the other two options—if someone wanted words to be special cased, they would've used sentence case / title case instead.

**Comment by TomLucidor** [comment]
When it comes to title casing vs ALLCAPS, what are the concern?
