### ISSUE TITLE
DeArrow looks up videos even when disabled

### ISSUE THREAD

**Issue by FatheredPuma81** [ajayyy/DeArrow#157]
Not sure if something changed or the servers are just incredibly slow today but it's incredibly apparent that DeArrow is asking for the **title** of every single video even if none of them are on the Allowlist. This simply shouldn't be happening. Will have to remove the extension at this rate because it's really inconvenient staring at a blank space for up to 10 seconds to see if I want to watch a video.

**Comment by ajayyy** [comment]
Could go to options -> copy debug info

It sounds more like the channel fetching request to YouTube is being slow

**Comment by FatheredPuma81** [comment]
{
    "debug": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60",
        "platform": "Win32",
        "language": "en",
        "extensionVersion": "1.2.22"
    },
    "config": {
        "allowExpirements": true,
        "alreadyActivated": true,
        "channelOverrides": {
            "Linus Tech Tips": "Cmn7K3tOVgCsuJDXCyrXiQBCrt8R6MOFC1Qe"
        },
        "customConfigurations": {
            "Cmn7K3tOVgCsuJDXCyrXiQBCrt8R6MOFC1Qe": {
                "defaultToCustom": true,
                "name": "Fixing Linus",
                "replaceThumbnails": false,
                "replaceTitles": true,
                "thumbnailFallback": 2,
                "titleFormatting": null
            }
        },
        "darkMode": true,
        "defaultToCustom": true,
        "firefoxOldContentScriptRegistration": false,
        "importedConfig": true,
        "lastIncognitoStatus": false,
        "lastVersion": "1.2.10",
        "replaceThumbnails": false,
        "replaceTitles": false,
        "showDonationLink": true,
        "showUpsells": true,
        "thumbnailCacheUse": 0,
        "thumbnailReplacements": 4416,
        "titleFormatting": -1,
        "titleReplacements": 11872,
        "vip": false,
        "donateClicked": 0,
        "invidiousInstances": 0,
        "keepUnsubmitted": true,
        "keepUnsubmittedInPrivate": false,
        "shouldCleanEmojis": true,
        "serverAddress": "Default server address",
        "thumbnailServerAddress": "https://dearrow-thumb.ajay.app",
        "fetchTimeout": 7000,
        "startLocalRenderTimeout": 2000,
        "renderTimeout": 25000,
        "showGuidelineHelp": true,
        "thumbnailFallback": 0,
        "thumbnailFallbackAutogenerated": 0,
        "extensionEnabled": true,
        "alwaysShowShowOriginalButton": false,
        "showOriginalOnHover": false,
        "useCrowdsourcedTitles": true,
        "titleMaxLines": 3,
        "showInfoAboutRandomThumbnails": false,
        "showIconForFormattedTitles": true,
        "countReplacements": true,
        "activated": true,
        "freeAccessWaitingPeriod": 259200000,
        "showActivatedMessage": false
    }
}

**Comment by ajayyy** [comment]
I was able to find the case where this happens thanks! Working on it now
