### ISSUE TITLE
Please get rid of the nag to pay for DeArrow.

### ISSUE THREAD

**Issue by NicoTheCinderace** [ajayyy/DeArrow#158]
Look, I apologize if this is the wrong means of voicing my frustration, and I get that these things are expensive to develop, but **stop** making me pay for the product.

I get that it's 1$, but if you're forcing me to pay for a product that was originally free, That's not cool at **all.**

Take away the "Free License" thing, and leave optional donations, instead of demanding that people pay money just to keep using it. A dollar or not, it's insidious, imo.

**Comment by ajayyy** [comment]
It only asks once when you install it. If you have a free license, you are never asked to pay. It does not try to nag you into paying. If you already were using it for free, it never asks you to pay either.

**Comment by 0x416c69** [comment]
@ajayyy I just wanted to say your way of monetization is very cool and genius, honestly due to the country I live in, I cannot afford to pay $1 but I understand why you make us wait for 3days. I'd pay the $1 if I could. Keep up the good job!

**Comment by ajayyy** [comment]
thanks :)

**Comment by 0x416c69** [comment]
@ajayyy I'm sure you've taken good care of the security logic behind this, i.e. if an attacker requests a free access for like 10,000 times with unique IPs and browser info there are clever ways to circumvent this, right?

**Comment by NicoTheCinderace** [comment]
> It only asks once when you install it. If you have a free license, you are never asked to pay. It does not try to nag you into paying. If you already were using it for free, it never asks you to pay either.
> 
> The product was not "originally free", as it was written on the page since the start, it was free forever for anyone who installed during the beta period, which lasted 4 months.


I was already using it for free when it started nagging me about wanting to pay. I uninstalled and reinstalled it, thinking it was a glitch at first.

**Comment by ajayyy** [comment]
That is definetly a glitch, that is not supposed to happen, sorry. My guess is that the extension storage somehow got reset.

Here's a key to fix it

F4tZs-cb353

**Comment by NicoTheCinderace** [comment]
> That is definetly a glitch, that is not supposed to happen, sorry. My guess is that the extension storage somehow got reset.
> 
> Here's a key to fix it
> 
> F4tZs-cb353

Thanks, it fixed it. Apologies for assuming you had ill will - It just randomly decided to act as if I didn't have DeArrow anymore. :(
