### ISSUE TITLE
DeArrow license should be kept when reinstalling DeArrow

### ISSUE THREAD

**Issue by GeekCornerGH** [ajayyy/DeArrow#163]
Hello everyone,

Thanks for the hard work on DeArrow so far. Really aperciate it.
However, I had an issue with DeArrow with was resolved by reinstalling the extension. I installed it when it was fully free. But when reinstalling the addon, I had to wait 48 hours.
Imho, when reinstalling the addon, you shouldn't have to wait 48 hours. Waiting for first-time installation is fine tho.

Thanks for your understanding.

**Comment by ajayyy** [comment]
It's not possible to save this info. What you need to do is copy the license key from the settings. If you forgot to copy, you can email me and I'll give you one right away

**Comment by GeekCornerGH** [comment]
Good to know, I’ll copy it and save it to my Bitwarden. Can I use the same for all browsers or not?

Thanks>

**Comment by ajayyy** [comment]
Yes
