### ISSUE TITLE
Show original titles by default with button to change it manually (Show Crowdsourced Titles/Details) 

### ISSUE THREAD

**Issue by gilangkpg** [ajayyy/DeArrow#169]
Hello,

I want to make a feature request to show original video titles by default but with a button to show crowdsourced title button next to it.

Kind of like the current implementation of "Show Original Details" button but the other way around. Because as of now I usually prefer the original titles of videos and only occasionally want to see the non-clickbait/crowdsourced titles instead.

Cheers

**Comment by ajayyy** [comment]
There is an option for this in behavior

**Comment by gilangkpg** [comment]
> There is an option for this in behavior

Sorry but can you elaborate? If I disable the replace title (and thumbnail) slider there's no longer a button next to a title to show the crowdsourced title.

I have to enable the replace title slider from extension menu which is different from my request. As with a button appearing next to a title I would have know if a video have a crowdsourced title available. And as of now is I disable both replace title and thumbnail slider there's no indication as to which video have custom title etc.

Hope you understand I mean.

Cheers

**Comment by ajayyy** [comment]
![Screenshot_20231027-134626654 (1)](https://github.com/ajayyy/DeArrow/assets/12688112/ca29c6b5-6da9-4367-bf21-ca5411da60df)

**Comment by gilangkpg** [comment]
Ok I'm stupid, thank you!
