### ISSUE TITLE
handling "empty" titles (zwsp, zwnj, etc)

### ISSUE THREAD

**Issue by EmeraldSnorlax** [ajayyy/DeArrow#170]
the submissions menu does not open on videos with "empty" titles (e.g. https://www.youtube.com/watch?v=UxM5UgpXYM4)

also, better guidelines are needed to explicitly cover what to do with them, especially artistic videos. 

discord conversation: https://canary.discord.com/channels/603643120093233162/897699762738966558/1167549682076106863

mentioned points (for the above video, which is a song):
- artist -- datetime
- artist -- first lyric
- artist -- arbitrary title based on vibes

all aren't great, but can't think of any others atm.

for the example video in the first line of the issue, [we seem to have settled](https://canary.discord.com/channels/603643120093233162/897699762738966558/1167558662898856026) on using the names of the song [as they appear on streaming services](https://canary.discord.com/channels/603643120093233162/897699762738966558/1167558358040068217). e.g. `/ / // / /`, but this doesn't seem like a catchall solution for all empty title videos, especially those where the empty title is an artistic choice for a fiction piece

**Comment by ajayyy** [comment]
All those related video titles were throwing me off
