### ISSUE TITLE
bug: Video titles are not overriden until I disable and re-enable 

### ISSUE THREAD

**Issue by kintrix007** [ajayyy/DeArrow#171]
Browser: Mozilla Firefox 119.0

When Loading a Youtube page, only the thumbnails are correcly overriden, the titles stay the origin until I disable then re-enable DeArrow in its settings.

Before toggling off and on:
![image](https://github.com/ajayyy/DeArrow/assets/60898798/29e1dedc-709c-489c-b462-169b1c20d07e)

After toggling off and on:
![image](https://github.com/ajayyy/DeArrow/assets/60898798/683f44d6-63b1-4c3e-83fa-6e4616ecde09)

**Comment by ajayyy** [comment]
Could you send any other extensions, userscripts and userstyles you have

**Comment by kintrix007** [comment]
Of course!
Here are the extensions:
![image](https://github.com/ajayyy/DeArrow/assets/60898798/22f43cd7-6f99-414f-970e-61b230177831)

I do not have any userscripts or userstyles active other than these.

Not that you asked, I feel like the Youtube Anti-Translate extension could be the one messing with it.
I will try disabling it and see if it makes a difference.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/DeArrow/issues/88
