### ISSUE TITLE
bugged names and descriptions in the Firefox Add-ons Store

### ISSUE THREAD

**Issue by WAZAAAAA0** [ajayyy/DeArrow#175]
The name and description are wrong in most languages of the Firefox Extensions Store. They are shown as `__MSG_deArrowFullName__` and `__MSG_deArrowDescription__` respectively.

DEMONSTRATION:
![](https://i.imgur.com/vlD0s6Z.png)

EXAMPLE LINK:
https://addons.mozilla.org/it/firefox/addon/dearrow/

INCORRECT STORE LANGUAGES:
`bn ca de el fa fi he hi id it lv ml ms nl no pt_BR pt_PT sk sr ta te th tr vi zh_CN zh_TW`

CORRECT STORE LANGUAGES:
`ar bg cs da en es et fi fr hr hu ja ko pl ro ru sv uk`

**Comment by ajayyy** [comment]
Fixed
