### ISSUE TITLE
Option to desaturate thumbnails

### ISSUE THREAD

**Issue by Exponential-Workload** [ajayyy/DeArrow#177]
In some cases, it may be nice to have entirely de-saturated thumbnails as an option, to further reduce the chances of clicking something your brain actually doesn't want to click (getting clickbaited). This issue serves as a suggestion to add some option, which should likely default to disabled, that simply styles thumbnails with `filter: grayscale(1);`, to avoid said issue. It may also be useful for the user to be able to specify how much to desaturate the thumbnail by (which would change the `1` in `filter: grayscale(1);` to an arbitrary user-provided value)
It may also be worth adding a sub-option that also grayscales the hover preview of the video to maintain consistency with that section of the screen being blurred.

Implementing a basic version of this can be done with just a few lines in a userscript, however it may be nicer to integrate this directly into the extension most people will already be using to be less distracted by others' content (thumbnails, titles).

**Comment by jgoedde** [comment]
Do you mean desaturated original thumbnails (clickbait thumbnails) or desaturated user submitted/random video thumbnails - or both? I would say this feature only makes sense when the option "replace thumbnails" is disabled.

**Comment by Exponential-Workload** [comment]
> Do you mean desaturated original thumbnails (clickbait thumbnails) or desaturated user submitted/random video thumbnails - or both? I would say this feature only makes sense when the option "replace thumbnails" is disabled.

I'm pretty sure I was referencing both; not like it'd hurt to have for both

The issue is some channels create generally "vibrant" content, meaning even de-arrow'ed thumbnails they look more "appealing" to click on than they should be.

Additionally, some thumbnails haven't been de-arrow'ed yet.

**Comment by jgoedde** [comment]
Yes, I liked the idea too. Currently working on implementing that. Looks like a pretty easy change though.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/DeArrow/pull/244
