### ISSUE TITLE
Channel page sometimes shows titles and thumbnails from other videos

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/DeArrow#18]
https://discord.com/channels/603643120093233162/603643299961503761/1117153486673559572

> go on youtube home page
click directly to a recommended video's channel
switch to the videos tab
click the youtube logo to go back to the home page
click on an other video's channel, go to the videos tab
titles may be screwed up, if not keep trying

https://discord.com/channels/603643120093233162/603643299961503761/1117155926789599254

**Comment by mschae23** [comment]
I can also consistently reproduce this:

- Go on the videos tab of a channel with title submissions (and let it fully load, not sure if that's required, though)
- Open another channel (maybe needs title submissions too? Not sure), for example using search, and switch to the videos tab.

Some videos retain the title from the previously visited channel. Also, only very few thumbnails load.

Disabling and enabling the extension in the popup doesn't have any effect at all, however scrolling until more videos load fixes all videos.

**Comment by Woodie-07** [comment]
I believe the issue still occurs sometimes when no channels clicked have submissions. I'm still trying to reproduce it and find all of the cases the issue happens in.

**Comment by Woodie-07** [comment]
It seems that once I click on a channel with title submissions, the next couple few channels I click will have their titles overwritten with the title submissions, and then it'll go back to normal until I click on a channel with title submissions again.
