### ISSUE TITLE
Add "buy now" button to homepage

### ISSUE THREAD

**Issue by oliverisaac** [ajayyy/DeArrow#190]
Hey, just dropping a note to let you know that it's difficult to find the buy now button if you don't have the extension installed.

It'd be great to get a buy now button added to the homepage and/or the GitHub repo to make the purchase process smoother. (I wanted to buy it from a different device than I had installed the extension).

**Comment by ajayyy** [comment]
Right now it only appears after selecting a platform (Chrome, Firefox or Edge). The reason is that the Safari one follows a different process and the android one is free. Not sure where to put it on the home page that would make sense

**Comment by ajayyy** [comment]
Added a link in the readme
