### ISSUE TITLE
Get the location/address of plugin buyer from PayPal

### ISSUE THREAD

**Issue by einekratzekatze** [ajayyy/DeArrow#193]
PayPal should provide you with it already, so asking beforehand doesn't seem necessary.
Should you use a 3rd party for the payment and not PayPal directly, which doesn't support this, you should consider getting rid of it.
As site notes: You should add a +VAT to all $1 claims. In most countries, you'd expect prices to be with VAT (or at least such a note). You may also want to note how much you actually get from that $1 from each payment, so people may choose the one that leaves more for you.

**Comment by ajayyy** [comment]
Hi, the payment process is handled by itch.io, so I cannot change those steps. I'll add a note on the payment page though
