### ISSUE TITLE
A glitch in a Vietnamese title.

### ISSUE THREAD

**Issue by khangquangtran** [ajayyy/DeArrow#203]
Windows 10 Home
Google Chrome 120.0.6099.109
Video link: https://www.youtube.com/watch?v=SthohHkvGd8

Original Vietnamese title (with original lowercase/uppercase and punctuation): "Lindo HOẢNG HỐT Khi Lần Đầu Thấy Quả Bầu Việt Nam To Như Vậy !!!"

Replacement title by DeArrow, Title Case: "Lindo Hoảng Hốt Khi Lần Đầu Thấy Quả Bầu Việt Nam to Như Vậy"

The glitch is at the "to" word in the replacement title. In Vietnamese, "to" is "big" (an adjective), not the "to" word in English. I even tried "To" in the suggesting text box to make it capitalized in the Title Case, but the result is still lowercase "to". I need "to" to be capitalized in Title Case like other words in the title.

Thank you!

**Comment by ajayyy** [comment]
Fixed in 6ef237698cfa839cd4e980bcdb561004fdd3f043

![image](https://github.com/ajayyy/DeArrow/assets/12688112/3df13186-e1fb-4d3a-8bec-239020db703c)

New option added for this. Unfortunately the language detection wasn't good enough in my tests to be enabled for everyone by default.
