### ISSUE TITLE
Video stuttering in Firefox / v1.3

### ISSUE THREAD

**Issue by xrstf** [ajayyy/DeArrow#209]
For roughly a week or so (so maybe related to v1.3) I am experiencing issues when opening/reloading a YouTube video tab. During the first like 10 seconds, the video would freeze and only audio would keep playing. It seems that once the page has "settled", skipping around in the video works just fine.

I noticed that disabling DeArrow makes the problem go away. While the video is stuttering, I also cannot open the DeArrow extension popup from the Firefox menu bar.

* OS: Windows 10 x64 (German)
* Browser: Firefox 121.0 (Norsk Bokmål)

Configuration (not sure why it says `last_version=1.2.10`, the UI shows v1.3):

```json
{
   "firefoxOldContentScriptRegistration": false,
   "showActivatedMessage": true,
   "freeActivation": false,
   "alreadyActivated": true,
   "titleReplacements": 9410,
   "userID": "...",
   "allowExpirements": true,
   "showDonationLink": false,
   "showUpsells": true,
   "darkMode": true,
   "licenseKey": "...",
   "extensionEnabled": false,
   "lastVersion": "1.2.10",
   "shouldCleanEmojis": true,
   "importedConfig": true,
   "showInfoAboutRandomThumbnails": false,
   "activated": true,
   "thumbnailReplacements": 121932,
   "vip": false,
   "donateClicked": 0,
   "invidiousInstances": [],
   "keepUnsubmitted": true,
   "keepUnsubmittedInPrivate": false,
   "titleFormatting": -1,
   "onlyTitleCaseInEnglish": false,
   "serverAddress": "https://sponsor.ajay.app",
   "thumbnailServerAddress": "https://dearrow-thumb.ajay.app",
   "fetchTimeout": 7000,
   "startLocalRenderTimeout": 2000,
   "renderTimeout": 25000,
   "thumbnailCacheUse": 2,
   "showGuidelineHelp": true,
   "thumbnailFallback": 0,
   "thumbnailFallbackAutogenerated": 0,
   "defaultToCustom": true,
   "alwaysShowShowOriginalButton": false,
   "showOriginalOnHover": false,
   "replaceTitles": true,
   "replaceThumbnails": true,
   "useCrowdsourcedTitles": true,
   "titleMaxLines": 3,
   "channelOverrides": {},
   "customConfigurations": {},
   "showIconForFormattedTitles": true,
   "countReplacements": true,
   "ignoreAbThumbnails": true,
   "freeTrialStart": null,
   "freeTrialEnded": false,
   "freeAccessRequestStart": null,
   "freeAccessWaitingPeriod": 259200000,
   "lastIncognitoStatus": false
}
```

**Comment by ObscenityIB** [comment]
This is also an issue for me, except the video doesn't come back, the whole YouTube tab is frozen even after DeArrow is disabled, and the browser needs to be restarted.

The browser displays `"DeArrow" is slowing down Nightly. To speed up your browser, stop that extention. Learn More   [Stop]`

DeArrow v1.3
Firefox v123.0a1 (2023-12-31)

**Comment by ajayyy** [comment]
Try on 1.4
