### ISSUE TITLE
Dark mode compatibility

### ISSUE THREAD

**Issue by saitejal** [ajayyy/DeArrow#215]
Hi Community,

This addon works great in light mode. In dark mode, its very difficult to distinguish if the title is DeArrowed on YT.

**Comment by ajayyy** [comment]
It is designed to work in dark mode. Please specify something specific that you think should be changed

**Comment by saitejal** [comment]
Thank you for the quick comment! There are three different states of DeArrow icon on YT page as follows (in my usage):
- Community modified title available/ not available
- DeArrow enabled/ disabled for a specific video

<img width="656" alt="Screenshot 2024-01-11 at 8 11 47 PM" src="https://github.com/ajayyy/DeArrow/assets/11802394/92e8ca35-0687-45ca-959a-a8f3cdf31072">

<img width="652" alt="Screenshot 2024-01-11 at 8 11 28 PM" src="https://github.com/ajayyy/DeArrow/assets/11802394/00a94fe0-db62-4a10-81d8-dd26ad106cde">

In the dark mode picture (I'm using Firefox default system sync theme with YT default dark mode, no dark reader or any other plugin ) I'm unable to differentiate those 3 different states, but very clear in light mode.

It's nearly impossible to tell/ differentiate those states at first glance in dark mode compared to light mode. Another possible contributing factor to this could be the screen resolution / OS scaling/ page zoom level

<img width="62" alt="Screenshot 2024-01-11 at 8 22 50 PM" src="https://github.com/ajayyy/DeArrow/assets/11802394/95bdfbb0-1f07-40ca-95f6-4860f4936c73">
<img width="68" alt="Screenshot 2024-01-11 at 8 22 23 PM" src="https://github.com/ajayyy/DeArrow/assets/11802394/8220b71d-d39d-451e-8204-58e925b056bb">
<img width="629" alt="Screenshot 2024-01-11 at 8 09 44 PM" src="https://github.com/ajayyy/DeArrow/assets/11802394/eced3da4-a12a-4cba-9b1a-20f3b92b05cc">
<img width="652" alt="Screenshot 2024-01-11 at 8 08 19 PM" src="https://github.com/ajayyy/DeArrow/assets/11802394/5bc67e5a-83d7-44c3-8ffd-b999f15dc577">

**Comment by ajayyy** [comment]
https://github.com/ajayyy/DeArrow/issues/205
