### ISSUE TITLE
Title replacement results in the title disappearing

### ISSUE THREAD

**Issue by NonVolatileHuman** [ajayyy/DeArrow#219]
I tried this on Firefox and Edge. When I click the circle on the right of the video title to change it from “original” to “suggested” it just disappears for 5 secs and the original title re-appears by itself. I'm on ver.1.4

**Comment by ajayyy** [comment]
This is due to the server going down

**Comment by everypizza1** [comment]
> This is due to the server going down

Is there a timeframe for the servers to be restored?

**Comment by ajayyy** [comment]
No, but I am working on it
