### ISSUE TITLE
"Show Original Details on Hover" Inverts Title

### ISSUE THREAD

**Issue by ElvenChaos** [ajayyy/DeArrow#220]
When "Show Original Details on Hover" is enabled, the old title is visible until the button is hovered, which then shows you the new title. I have only tried this with FireFox.

**Comment by ajayyy** [comment]
You probably enabled "Default To Original Video Information" in the main options

**Comment by ElvenChaos** [comment]
You are absolutely right. I thought I double-checked the options well, but I missed it >>;
