### ISSUE TITLE
Add option to show only user submitted thumbnails

### ISSUE THREAD

**Issue by n1cKz1** [ajayyy/DeArrow#221]
Currently, if a video doesn't have a user submitted thumbnail available sometimes a thumbnail of a random video time is automatically generated instead. It would be nice if there was an option available to only show user submitted thumbnails as these random generated thumbnails are more often than not way off.

**Comment by ajayyy** [comment]
It's in the settings

**Comment by n1cKz1** [comment]
Possible to add an API parameter for it?

**Comment by ajayyy** [comment]
It's possible to do in the current API yes
