### ISSUE TITLE
 Thumbnails not getting replaced

### ISSUE THREAD

**Issue by silentJET85** [ajayyy/DeArrow#224]
The option to "Show a thumbnail auto-generated by Youtube" instead shows the original thumbnail. This happens to me in Ungoogled Chromium and Brave. It works properly in Firefox and Librewolf.

**Comment by ajayyy** [comment]
Can you go to options, misc, copy debug info?

**Comment by silentJET85** [comment]
{
    "debug": {
        "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "platform": "Linux x86_64",
        "language": "en-US",
        "extensionVersion": "1.5"
    },
    "config": {
        "activated": true,
        "allowExpirements": true,
        "alreadyActivated": true,
        "alwaysShowShowOriginalButton": true,
        "channelOverrides": {},
        "countReplacements": true,
        "customConfigurations": {},
        "darkMode": false,
        "defaultToCustom": true,
        "donateClicked": 0,
        "extensionEnabled": true,
        "fetchTimeout": 7000,
        "firefoxOldContentScriptRegistration": false,
        "ignoreAbThumbnails": true,
        "importedConfig": true,
        "invidiousInstances": 0,
        "keepUnsubmitted": true,
        "keepUnsubmittedInPrivate": false,
        "lastIncognitoStatus": false,
        "onlyTitleCaseInEnglish": false,
        "renderTimeout": 25000,
        "replaceThumbnails": true,
        "replaceTitles": true,
        "serverAddress": "Default server address",
        "shouldCleanEmojis": true,
        "showActivatedMessage": false,
        "showDonationLink": true,
        "showGuidelineHelp": true,
        "showIconForFormattedTitles": true,
        "showInfoAboutRandomThumbnails": false,
        "showLiveCover": false,
        "showOriginalOnHover": false,
        "showUpsells": true,
        "startLocalRenderTimeout": 2000,
        "thumbnailCacheUse": 2,
        "thumbnailFallback": 3,
        "thumbnailFallbackAutogenerated": 1,
        "thumbnailReplacements": 41532,
        "thumbnailServerAddress": "https://dearrow-thumb.ajay.app",
        "titleFormatting": 1,
        "titleMaxLines": 3,
        "titleReplacements": 4529,
        "useCrowdsourcedTitles": true,
        "vip": false,
        "freeAccessWaitingPeriod": 259200000
    }
}

**Comment by ajayyy** [comment]
What videos does this issue occur on?

**Comment by silentJET85** [comment]
Seems to be all videos.

**Comment by ajayyy** [comment]
Can you send a screenshot

**Comment by silentJET85** [comment]
![Screenshot_20240126_204218](https://github.com/ajayyy/DeArrow/assets/81664312/75782950-7a7e-43f0-a352-94827c3fd264)

**Comment by ajayyy** [comment]
Can you try disabling your other extensions?

**Comment by silentJET85** [comment]
Okay, I tried disabling them, but it didn't make any difference.

**Comment by nosam555** [comment]
I'm having this same issue. Here's my debug info:

{
    "debug": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "platform": "Win32",
        "language": "en-US",
        "extensionVersion": "1.5"
    },
    "config": {
        "activated": true,
        "allowExpirements": true,
        "alreadyActivated": true,
        "channelOverrides": {
            "UCwpHKudUkP5tNgmMdexB3ow": "Fu5DV3AyC4rV9ytOsE7b4XaCxtO775p5trPA"
        },
        "customConfigurations": {
            "Fu5DV3AyC4rV9ytOsE7b4XaCxtO775p5trPA": {
                "defaultToCustom": null,
                "name": "Allow Titles",
                "replaceThumbnails": null,
                "replaceTitles": false,
                "shouldCleanEmojis": null,
                "thumbnailFallback": null,
                "thumbnailFallbackAutogenerated": null,
                "titleFormatting": null,
                "useCrowdsourcedTitles": null
            }
        },
        "darkMode": true,
        "firefoxOldContentScriptRegistration": false,
        "freeAccessWaitingPeriod": 43200000,
        "importedConfig": true,
        "lastIncognitoStatus": false,
        "shouldCleanEmojis": false,
        "showActivatedMessage": true,
        "showDonationLink": true,
        "showInfoAboutRandomThumbnails": false,
        "showUpsells": true,
        "thumbnailFallback": 3,
        "thumbnailFallbackAutogenerated": 1,
        "thumbnailReplacements": 246767,
        "titleFormatting": 1,
        "titleReplacements": 34713,
        "vip": false,
        "donateClicked": 0,
        "invidiousInstances": 0,
        "keepUnsubmitted": true,
        "keepUnsubmittedInPrivate": false,
        "onlyTitleCaseInEnglish": false,
        "serverAddress": "Default server address",
        "thumbnailServerAddress": "https://dearrow-thumb.ajay.app",
        "fetchTimeout": 7000,
        "startLocalRenderTimeout": 2000,
        "renderTimeout": 25000,
        "thumbnailCacheUse": 2,
        "showGuidelineHelp": true,
        "showLiveCover": true,
        "extensionEnabled": true,
        "defaultToCustom": true,
        "alwaysShowShowOriginalButton": false,
        "showOriginalOnHover": false,
        "replaceTitles": true,
        "replaceThumbnails": true,
        "useCrowdsourcedTitles": true,
        "titleMaxLines": 3,
        "showIconForFormattedTitles": true,
        "countReplacements": true,
        "ignoreAbThumbnails": true
    }
}

**Comment by SirAbhi13** [comment]
Facing the same issue on Brave Browser, works fine on Librewolf.
Experiencing this on Windows 11. I haven't added any new extension that I didn't have before, everything is same (Librewolf has the same extensions if it makes any difference)


{
    "debug": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
        "platform": "Win32",
        "language": "en-GB",
        "extensionVersion": "1.5"
    },
    "config": {
        "activated": true,
        "allowExpirements": true,
        "alreadyActivated": true,
        "channelOverrides": {},
        "customConfigurations": {},
        "darkMode": true,
        "firefoxOldContentScriptRegistration": false,
        "freeAccessWaitingPeriod": 43200000,
        "importedConfig": true,
        "lastIncognitoStatus": true,
        "showActivatedMessage": true,
        "showDonationLink": true,
        "showInfoAboutRandomThumbnails": false,
        "showUpsells": true,
        "thumbnailFallback": 3,
        "thumbnailReplacements": 160885,
        "titleReplacements": 3133,
        "vip": false,
        "donateClicked": 0,
        "invidiousInstances": 0,
        "keepUnsubmitted": true,
        "keepUnsubmittedInPrivate": false,
        "titleFormatting": 1,
        "shouldCleanEmojis": true,
        "onlyTitleCaseInEnglish": false,
        "serverAddress": "Default server address",
        "thumbnailServerAddress": "https://dearrow-thumb.ajay.app",
        "fetchTimeout": 7000,
        "startLocalRenderTimeout": 2000,
        "renderTimeout": 25000,
        "thumbnailCacheUse": 2,
        "showGuidelineHelp": true,
        "thumbnailFallbackAutogenerated": 0,
        "showLiveCover": true,
        "extensionEnabled": true,
        "defaultToCustom": true,
        "alwaysShowShowOriginalButton": false,
        "showOriginalOnHover": false,
        "replaceTitles": true,
        "replaceThumbnails": true,
        "useCrowdsourcedTitles": true,
        "titleMaxLines": 3,
        "showIconForFormattedTitles": true,
        "countReplacements": true,
        "ignoreAbThumbnails": true
    }
}
