### ISSUE TITLE
Thumbnails Are Black on Channel Homepages “Featured” Videos

### ISSUE THREAD

**Issue by danispringer** [ajayyy/DeArrow#229]
Example: https://www.youtube.com/channel/UCJg-_LkT2C9uxGYVB2K63sg

I also tried adding that channel ID (`UCJg-_LkT2C9uxGYVB2K63sg`) to a new configuration (although I'm not sure if and how to "activate" said configuration)

Thanks

**Comment by danispringer** [comment]
https://www.youtube.com/watch?v=OpDVkuxe6FA

this seems to happen with random videos too. turning extension OFF and ON seems to temporarily fix, refresh bring issue up again.

Browser: Brave, 
MacBook: M1 Air
macos: Sonoma 14.3.1 (23D60)

**Comment by ajayyy** [comment]
@FatheredPuma81 If you have BlockTube installed, the latest version caused a problem with DeArrow. I just published 1.5.3 which fixes this issue

**Comment by FatheredPuma81** [comment]
> @FatheredPuma81 If you have BlockTube installed, the latest version caused a problem with DeArrow. I just published 1.5.3 which fixes this issue

Why must important extensions break one another D:<. Thank you for fixing someone else's problem.

**Comment by danispringer** [comment]
> Why must important extensions break one another D:<. Thank you for fixing someone else's problem.

Because: YouTube (i.e.: Google).
I hope that answers your question… ;)

**Comment by ajayyy** [comment]
The blocktube issue was fixed

**Comment by ajayyy** [comment]
What do you mean by featured? Can you send a screenshot?

**Comment by ajayyy** [comment]
I don't see any black thumbnails
