### ISSUE TITLE
All thumbnails are gray/all titles are missing until refresh

### ISSUE THREAD

**Issue by QuietMisdreavus** [ajayyy/DeArrow#230]
I seem to be in a similar boat to #137 and #206, but i feel like this situation is slightly different from the apparent causes they've got.

I'm running in Safari (v17.3.1) using the extension from the App Store (v1.5.5), and every time i load a page in a new tab, the thumbnails and titles fail to load. However, if i reload the page, the thumbnails and titles correctly load and the site displays as normal until i close the tab.

<img width="1509" alt="image" src="https://github.com/ajayyy/DeArrow/assets/5217170/1fdb5d8a-0d13-4357-85c8-1616daa5d060">

Extension list:

- Nearly everything from 1Blocker (which has a site override to ignore YouTube anyway)
- Bitwarden
- Cascadea (nothing that modifies YouTube though)
- Convusic
- Ivory
- Kagi
- NetNewsWire "Subscribe To Feed"
- Safarikai
- SponsorBlock
- StopTheMadness
- Superagent
- Tampermonkey
  - The only script i have installed is BetterTTV

No channel overrides set.

Uninstalling the extension (by moving the app to Trash) and reinstalling (by dragging the app out of Trash and reopening to add the extension back) allowed the correct behavior exactly once, before reverting to the bugged behavior.

<details>
<summary>Debug info</summary>

```json
{
    "debug": {
        "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15",
        "platform": "MacIntel",
        "language": "en-US",
        "extensionVersion": "1.5.5"
    },
    "config": {
        "titleReplacements": 9816,
        "vip": false,
        "alreadyActivated": true,
        "darkMode": false,
        "replaceThumbnails": true,
        "titleFormatting": -1,
        "thumbnailFallback": 0,
        "extensionEnabled": true,
        "shouldCleanEmojis": true,
        "thumbnailReplacements": 35777,
        "showInfoAboutRandomThumbnails": true,
        "alwaysShowShowOriginalButton": true,
        "allowExpirements": true,
        "showDonationLink": true,
        "showUpsells": true,
        "donateClicked": 0,
        "invidiousInstances": 0,
        "keepUnsubmitted": true,
        "keepUnsubmittedInPrivate": false,
        "onlyTitleCaseInEnglish": false,
        "serverAddress": "Default server address",
        "thumbnailServerAddress": "https://dearrow-thumb.ajay.app",
        "fetchTimeout": 7000,
        "startLocalRenderTimeout": 2000,
        "renderTimeout": 25000,
        "thumbnailCacheUse": 2,
        "showGuidelineHelp": true,
        "thumbnailFallbackAutogenerated": 0,
        "showLiveCover": true,
        "defaultToCustom": true,
        "showOriginalOnHover": false,
        "importedConfig": false,
        "replaceTitles": true,
        "useCrowdsourcedTitles": true,
        "titleMaxLines": 3,
        "channelOverrides": {},
        "customConfigurations": {},
        "showIconForFormattedTitles": true,
        "countReplacements": true,
        "ignoreAbThumbnails": true,
        "activated": true,
        "freeAccessWaitingPeriod": 259200000,
        "firefoxOldContentScriptRegistration": false,
        "lastIncognitoStatus": false,
        "showActivatedMessage": false
    }
}
```

</details>

**Comment by ajayyy** [comment]
What happens if you click a video while in this state?

**Comment by QuietMisdreavus** [comment]
The video page loads, and the title/thumbnail replacement starts working for the video itself and the recommendations.

**Comment by QuietMisdreavus** [comment]
Oh, this is interesting, though. I finished watching that video and clicked the sidebar link back to my Subscriptions page. Those thumbnails and titles loaded correctly. However, when i navigated to the home page, i got the same behavior as #206:

<img width="1512" alt="image" src="https://github.com/ajayyy/DeArrow/assets/5217170/43235f8f-92a1-4ec9-ad04-85d06f458248">

**Comment by ajayyy** [comment]
Could you try disabling your other extensions?

This seems to be the function listening for new thumbnails appearing not working (since it falls back to also checking for thumbnails on page navigation, which is why it works for the first few)

**Comment by QuietMisdreavus** [comment]
Same behavior, though i went through the "click a video, click back to Subscriptions, click to Home" flow and the home page correctly loaded thumbnails and titles.

**Comment by IMNdi** [comment]
I had this too on Edge, blanks for all, refreshing did get blanks again, however clicking on a link generated thumbs and everything until the next page loaded. So as a result, I managed to make it load, I don't remember how, unfortunately. Right click link? Middle click? Click and back again?

Anyway, after 24 hours it just started working again and I assumed I was A/B tested by Youtube.

I also have some other weird issues over the next 48 hours, related to lazy loading things. For example, I clicked video A, had description A, title A, etc. Clicking a video from that page ( /v= ) managed to load the next video, but not details. Title was stuck as previous title, description was left over, comments did load on scroll down.

That also went away. 

I suspect it was YT A/B testing some UI. Common extensions with you: Bitwarden, TamperMonkey (YT age restriction bypass) and Sponsorblock.

**Comment by ajayyy** [comment]
And in this case, what was displaying? No thumbnails, only some?

**Comment by QuietMisdreavus** [comment]
1. Loaded subscriptions page, no thumbnails visible
2. Ran code
3. Clicked a video - during page nav the thumbnails started appearing but then the page switched
4. Recommendations on video page were visible
5. Clicked back, thumbnails were visible on subscriptions page
6. Scrolled down - upon loading a new batch of links, new thumbnails were not visible
