### ISSUE TITLE
localization: default to sentence case for non-english titles

### ISSUE THREAD

**Issue by anabelle2001** [ajayyy/DeArrow#231]
Very few languages capitalize each word in a title:

https://linguistics.stackexchange.com/questions/32182/what-are-the-title-capitalization-rules-in-some-languages

https://ux.stackexchange.com/questions/72790/is-it-default-that-an-english-version-is-always-title-case-while-other-language/72813#72813

By default, de-arrow should use "Sentence case" rules for non-english titles.

**Comment by ajayyy** [comment]
![image](https://github.com/ajayyy/DeArrow/assets/12688112/3689bf44-5c6a-40e5-9c73-e814b3069e42)

This is already the case, but the language detection is not perfect
