### ISSUE TITLE
Tooltip in sidebar hides video title

### ISSUE THREAD

**Issue by trumad** [ajayyy/DeArrow#252]
**The suggested videos sidebar has this odd behaviour when "Show Original Details on Hover"  is enabled:**

<img width="453" alt="image" src="https://github.com/ajayyy/DeArrow/assets/9892909/3b0b01c3-6aea-46d2-aab2-e147296684b4">

<img width="455" alt="image" src="https://github.com/ajayyy/DeArrow/assets/9892909/cf25e1c9-1f96-47c5-9992-d8f972a6301f">

There are a couple of issues. The original title gets covered by the tooltip after a second. Also, the text in the tooltip seems to be right-aligned or something? It's not centered on the tooltip and makes it look like it is going off the screen. It's also a bit unnecessary since it's just repeating the information already shown.

**Here is the tooltip's behaviour when "Show Original Details on Hover" is disabled:**

<img width="451" alt="image" src="https://github.com/ajayyy/DeArrow/assets/9892909/c7a68b45-8604-45fa-b83d-777eb38169fd">

It looks like it has a lot less padding, and doesn't get in the way.

I'd personally be happy if there is no tooltip at all when "Show Original Details on Hover"  is enabled. I don't see the need for it when the title natively changes on hover.

**Comment by ajayyy** [comment]
This is a browser problem. The extension cannot control the kook of the tooltip

**Comment by trumad** [comment]
oh, I didn't realise sorry! I presumed it was your tooltip since it appears when hovering on the blue circle icon. Something about changing the title seems to change the CSS of the tooltip somehow... I'll see if it's something I can fix with tampermonkey.
