### ISSUE TITLE
Rating accuracy of original title to attribute clickbait score to youtubers

### ISSUE THREAD

**Issue by oxysoft** [ajayyy/DeArrow#256]
When submitting a new title, users can also rate the accuracy of the original title. This allows a clickbait score to be calculated, which is then paired with a new _syntax highlighting_ for video titles. In this manner, unknown channels with a high clickbait score can be automatically shown in red to indicate to the user that they can save their time and sanity by not venturing on this channel. Titles which have been rewritten by DeArrow are always in blue to indicate that they are accurate.

**Comment by ajayyy** [comment]
Out of scope

As described on the website

> It's no one's fault. It's a system that creates a race to the bottom.

**Comment by oxysoft** [comment]
Aye fair enough
