### ISSUE TITLE
(Feature Request) Add option to use crowdsourced thumbnails in playlist previews

### ISSUE THREAD

**Issue by qxxst** [ajayyy/DeArrow#265]
![nSTTDTt](https://github.com/ajayyy/DeArrow/assets/31394614/9fe5eba1-6060-421e-a296-300b9acf1896)

Currently, playlists always use the original thumbnail of the first video in the playlist, which can be confusing. I would like an option for this to be replaced with the crowdsourced thumbnail.

**Comment by ajayyy** [comment]
Can you send the url? Right now it dues replace it in many playlist UIs
