### ISSUE TITLE
"Missing-thumbnail-YouTube.jpg" on random videos with Replace Thumbnails disabled

### ISSUE THREAD

**Issue by FatheredPuma81** [ajayyy/DeArrow#271]
![Screenshot_3](https://github.com/ajayyy/DeArrow/assets/38575406/8525671c-0866-4480-8f33-f5e2e72a3537)
Happening on completely random videos on completely random channels. Only consistent thing is it's permanent for that specific video. 
DeArrow is disabled by default and is set to only replace titles on Blacklisted channels.

**Comment by ajayyy** [comment]
#270
