### ISSUE TITLE
Not working anymore on Chrome?

### ISSUE THREAD

**Issue by SirJorb** [ajayyy/DeArrow#274]
Recently I've noticed that the extension doesn't seem to work properly on Chrome anymore. I can still submit new titles and thumbnails, but they don't actually display anymore (instead showing the original title and thumbnail 100% of the time, even after submitting a new one).

Does still seem to work fine on Firefox, though, and new names/thumbnails submitted on Chrome will still appear on Firefox.

**Comment by ajayyy** [comment]
Have you disabled the extension? Click the DeArrow icon in the top right corner of your browser (might have to click the puzzle piece). Then toggle the enabled slider

**Comment by SirJorb** [comment]
....apparently that was, in fact, it. Apparently I have the mental capacity of a 5 year old lmao. Thanks for the help.
