### ISSUE TITLE
Dearrow is merging two video titles together incorrectly

### ISSUE THREAD

**Issue by 825i** [ajayyy/DeArrow#276]
See on this page, I have the titles of 2 videos merged together for some reason.

The real "changed" title is on the right in the green box and the title of another video is on the left in red.

![Screenshot 2024-06-28 172034](https://github.com/ajayyy/DeArrow/assets/58630825/789cb8e1-fd60-408e-abae-4d48436abaa1)

Here's the other video it pulled the title from incorrectly:
![Screenshot 2024-06-28 172135](https://github.com/ajayyy/DeArrow/assets/58630825/1f74c377-fbc7-4596-88e0-444468cb514c)

Things I have noticed:

1. It happens to about 1 in 10 videos
2. It only happens on videos I have not seen
3. But the WRONG title is always from a video I HAVE seen

Hope you guys can fix it.

**Comment by ajayyy** [comment]
Do you have another extension that modifies titles such as "clickbait remover"

**Comment by ajayyy** [comment]
You should be able to change the fallback formatting in DeArrow to replicate the functionality you were using in Clickbait Remover before
