### ISSUE TITLE
The website cant be reached

### ISSUE THREAD

**Issue by aidankinzett** [ajayyy/DeArrow#28]
The link to the website from the extension window (https://dearrow.ajay.app/) shows the below error for me in chromium

```
This site can’t be reached
Check if there is a typo in dearrow.ajay.app.
DNS_PROBE_FINISHED_NXDOMAIN
```

**Comment by ajayyy** [comment]
Yes sorry the website doesn't exist right now

**Comment by aidankinzett** [comment]
no worries, just checking you were aware
