### ISSUE TITLE
Better indication that DeArrow is disabled

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/DeArrow#281]
Maybe in the title for the current video show some icon that when clicked shows info. DeArrow with an X through it, and remove pencil (or reuse pencil ui for this)

**Comment by EliteMasterEric** [comment]
Same! I got really confused after I thought the extension was broken but I had accidentally pressed the Shift-E hotkey and didn't know what was up until I looked into it more.

**Comment by ajayyy** [comment]
871978c886d571fef22c340c077f54f47f90f824
