### ISSUE TITLE
Normalize stylized text in video titles

### ISSUE THREAD

**Issue by lnmiltz** [ajayyy/DeArrow#283]
There are some videos on YouTube that use stylized text in their titles, which is a little attention grabbing and prevents them from working with DeArrow's clickbait filters (like `!`, `...`, or all caps). Replacing them by hand works, but it'd be convenient if DeArrow handled them automatically.

![image](https://github.com/user-attachments/assets/7d6d57d8-cba6-4d01-a9fa-a1b4eff70c7e)

I don't know which parts of YouTube have the most titles like this. I'm not super familiar with VTubers, but I usually see some of these titles pop up when I watch a video with one, so that might be a good area of YouTube to look at to find these kinds of titles.

There's a JS function to normalize strings and one of the modes should work well for this (`"𝗠𝘆 𝗖𝗼𝗼𝗹 𝗧𝗶𝘁𝗹𝗲".normalize("NFKD")` results in `"My Cool Title"`). It shouldn't mess with diacritics. I think NFKD is the right mode to use, but it might be worth double checking here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize#compatibility_normalization

If you need sample text to test on, this site might be handy too: https://lingojam.com/FancyTextGenerator

**Comment by SuperStormer** [comment]
#78
