### ISSUE TITLE
Completly broken on Firefox 129.0.2

### ISSUE THREAD

**Issue by Lt-Scarecrow** [ajayyy/DeArrow#290]
![Screenshot 2024-08-28 163643](https://github.com/user-attachments/assets/18baef4b-6f61-4d07-9c58-8b9b273d2219)

![Screenshot 2024-08-28 163817](https://github.com/user-attachments/assets/fd7d68b7-0f31-4dad-9f12-8fa50e0a40d7)

Thumbnails are not loading and the extension isn't loading options or dropping down.

**Comment by ajayyy** [comment]
can you try uninstalling and reinstalling

**Comment by Lt-Scarecrow** [comment]
Ah well this is embarrassing. That seems to have done it. Thank you
