### ISSUE TITLE
Support Piped/Invidious submissions

### ISSUE THREAD

**Issue by shaedrich** [ajayyy/DeArrow#292]
> > Piped now has native support for DeArrow everywhere with [TeamPiped/Piped@9539d51](https://github.com/TeamPiped/Piped/commit/9539d51126c0a53f10d084d3fdbc2c677fb6ac28).
> 
> Well, for the frontend. However, as far as I know, one can't do any submissions yet. That would be quite helpful.

Are there any plans to implement that?

_Originally posted by @shaedrich in https://github.com/ajayyy/DeArrow/issues/39#issuecomment-2253730295_

**Comment by ajayyy** [comment]
That would be included in the other issue

**Comment by shaedrich** [comment]
That probably why it was ignored then …
