### ISSUE TITLE
Can Dearrow's concept be applied to reveal the names of privated/delisted videos?

### ISSUE THREAD

**Issue by Tenome** [ajayyy/DeArrow#296]
I think this is a common complaint. You go to a playlist or recent history, see a video that's been marked private, and have no idea which video it even was. The hypothetical extension would have to track everything you watch and then watch for a "privated" warning, though.

I got the idea from this [existing Chrome extension (haven't tried since I'm on Firefox)](https://chromewebstore.google.com/detail/youtube-deleted-videos-tr/nnmnfooidppdikklofabhimjllemfgje?hl=en-US)

Sorry to make a suggestion for another extension in an unrelated Git, I didn't know where else to put it. Feel free to close this, but it'd be cool if the idea was considered. Thanks for all the great work!

**Comment by ajayyy** [comment]
Use this https://greasyfork.org/en/scripts/430202-filmot-title-restorer

**Comment by Tenome** [comment]
Hmm, that only seems to work for playlists. Oh well, better than nothing I suppose.
