### ISSUE TITLE
Replace tab title

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/DeArrow#3]
.take

**Comment by ajayyy** [comment]
Sorry can I do this I have a plan

**Comment by mchangrh** [comment]
> can I do this I have a plan for it

sure, I'll link my code then

I release/ licence it under AGPL for use in ClickbaitExtension

**Comment by ajayyy** [comment]
https://github.com/ajayyy/DeArrow/commit/03c05c8c73712c7777124ce17b907d1c129a5558
