### ISSUE TITLE
Thumbnail overlays like video length and duration watched don't properly display on altered thumbnails

### ISSUE THREAD

**Issue by DatHypnoboi** [ajayyy/DeArrow#30]
The issue seems to fix itself when toggling "Show Original Details" on and off

When the page first loads:
![Screenshot 2023-06-10 231808](https://github.com/ajayyy/DeArrow/assets/25212257/37a93d07-6920-44d3-afc8-c41fe4036e18)

After selecting "Show Original Details"
![Screenshot 2023-06-10 231820](https://github.com/ajayyy/DeArrow/assets/25212257/3b984cd5-87a6-4976-8c04-213ca5b82de3)

After unselecting "Show Original Details"
![Screenshot 2023-06-10 231829](https://github.com/ajayyy/DeArrow/assets/25212257/c6d54f68-7855-4bca-b887-ffae249c6451)

**Comment by ajayyy** [comment]
Thanks, logged here #16
