### ISSUE TITLE
[Feature request] Dont show screenshot from "SponsorBlock" segments for thumbnails

### ISSUE THREAD

**Issue by khoalu** [ajayyy/DeArrow#300]
First, thank you for two wonderful extensions I am using right now: SponsorBlock and DeArrow.

Currently when selecting the option "show a screenshot at a random time" of "when no submitted thumbnail exists", DeArrow sometimes shows a screenshot from a sponsor segment in that video (currently I only encounter 2 cases out of ~150 thumbnails ).

I just want to ask if it is possible to combine the features of SponsorBlock and DeArrow so that DeArrow no longer show a screenshot from a known SponsorBlock segment.

**Comment by ajayyy** [comment]
It already does this. This might be caused by the dearrow generated thumbnail to be missing and it falling back to the YouTube autogenerated one. This has been happening because YouTube has been blocking and breaking the thumbnail generator for a few minutes of every hour
