### ISSUE TITLE
Thumbnail not visible on channel's shorts page

### ISSUE THREAD

**Issue by eleage8992** [ajayyy/DeArrow#303]
In the latest versions of Chrome, Brave Browser, Firefox, and LibreWolf, there is an issue where, when DeArrow is activated on a channel's Shorts page, and you attempt to scroll down for loading or sort the page by options such as "Latest," "Popular," or "Date," none of the thumbnails on the page are visible. After testing to check for the influence of other extensions, I found that this issue only occurs when DeArrow is activated. I hope this can be resolved quickly.

![Firefox_Screenshot_2024-10-27T07-11-15 212Z](https://github.com/user-attachments/assets/34dbbec9-4274-4b18-a19b-5bc5577084b6)

**Comment by eleage8992** [comment]
It appears that the problem has not been resolved. Why has this issue page been completed?

**Comment by ajayyy** [comment]
You have to wait for the extension store for your browser to approve the update
