### ISSUE TITLE
Feature Request: Add option for inverting `Original Video Information`

### ISSUE THREAD

**Issue by daUnknownCoder** [ajayyy/DeArrow#311]
![image](https://github.com/user-attachments/assets/9b625fe4-fb9a-4d1a-93e4-9ff6ace0e081)
![image](https://github.com/user-attachments/assets/172d523f-976a-499b-a28e-5840b199a338)

i mean have an option so that the default is the De-Arrow generated `Thumbnail` and `Title`, but there is a button to hover/click to see the original title

**Comment by ajayyy** [comment]
That's the default options

**Comment by daUnknownCoder** [comment]
> That's the default options

Nope, the current one looks like:

![image](https://github.com/user-attachments/assets/aaa7ce71-e9ec-44cb-97ad-e5bbd23f670a)
and on hovering/clicking on the DeArrow icon, you can see rebranded thumbnail+title (according to the options you chose btw)

![image](https://github.com/user-attachments/assets/24896d5a-5298-4efc-877f-7a9cf03d3d20)
i want it to look like this defaultly/add option

and on hovering/clicking on the DeArrow icon, you can see the original one

**Comment by ajayyy** [comment]
If you turn it off, it defaults to DeArrow information
