### ISSUE TITLE
Action verbs in titles

### ISSUE THREAD

**Issue by github-account1111** [ajayyy/DeArrow#312]
I have noticed an increased usage of action verbs in DeArrow titles recently. Examples:

- https://dearrow.minibomba.pro/video_id/D4ghgVq9z4M
- https://dearrow.minibomba.pro/video_id/N1VC2SiUaz0

Titles shouldn't have action verbs. It goes against the convention, looks amateur and takes away from the viewing experience.

In the first example, the title, *"Why I'm leaving X/Twitter for Bluesky,"* is mostly fine. It has a verb in it, and some would argue verbs in titles are problematic in general, but it's not an action verb. *"Twitter and Threads downrank links"* and its iteration, however, aren't good titles. They both use action verbs and, as a result, are both full sentences and read like something that should be a part of the main body of text.

In the second example, the title *"ARM-based Laptops are superior to older models, but the price is so high except Macbooks"* is even worse. This one comes with *two* action verbs (in addition to a host of other issues). Most other titles are just as bad. I even see one with a semicolon... On the other hand, *"Current landscape of laptops: Apple Silicon, Snapdragon X, Intel and AMD"* and *"Comparison of Snapdragon X chips to modern Intel, AMD and Apple Silicon chips,"* are both fine and informative titles. Ironically enough, the original title, *"The inconvenient truth about new laptops,"* is also a fine title and isn't clickbait.

This happens especially frequently in tech-related videos. The viewers of such videos may be less familiar with writing conventions. The problem is that the rest of us end up suffering for it.

I think the extension should discourage action verbs in particular and verbs in general in titles in some way.

**Comment by ajayyy** [comment]
We are not trying to summarize videos, so a title like "Why I'm leaving X/Twitter for Bluesky" is preferred over "Twitter and Threads downrank links"

**Comment by github-account1111** [comment]
Yes. It should be. That was my point. But DeArrow has been getting flooded with titles like "Twitter and Threads downrank links."

Preference isn't enough, as is apparent with the influx of frankly garbage titles. There should also be discouragement.
