### ISSUE TITLE
Button to show original details messes with the title layout

### ISSUE THREAD

**Issue by rraallvv** [ajayyy/DeArrow#314]
Often, I accidentally hover over the video title while reading it, which causes the DeArrow button to appear and change the title layout, making me start reading it again.

Is there a way to permanently hide the Show Original button or move it to a different location, like a corner of the thumbnail, so it doesn't disrupt the layout when it appears?
 
<img width="390" alt="Screen Shot 2024-12-15 at 10 16 26 AM" src="https://github.com/user-attachments/assets/125986fb-8192-4a8b-8d22-d6b3f83e4a00" />
<img width="389" alt="Screen Shot 2024-12-15 at 10 16 35 AM" src="https://github.com/user-attachments/assets/b25e6ec9-a777-45cf-b082-f7fd4bb7d9d3" />

**Comment by ajayyy** [comment]
#58
