### ISSUE TITLE
Any plans to use AI

### ISSUE THREAD

**Issue by rraallvv** [ajayyy/DeArrow#315]
Sorry if this has been suggested before. I also couldn't find how to start a discussion topic on this subject. Basically, most AI APIs could start adding features like understanding the content of images, and they already have the ability to do it with text. Since most clickbait thumbnails and titles follow a pattern, like using superlatives and exaggeration in both the title and thumbnail, I wonder if there are any plans to use AI in this extension.

**Comment by ajayyy** [comment]
> most clickbait thumbnails and titles follow a pattern

We're not trying to edit the title to be less "clickbaity". We need to rewrite the title to actually be describing the video. This can't be based on patterns in the original title

**Comment by virginviolet** [comment]
Isn't less clickbaity still an improvement over the original title? I imagine it could be the default title before a human title is submitted. But it sounds really confusing. The internet is already getting more and more confusing. I don't want AI by default. And people don't fully understand the goal of DA as it is, and this would make it worse.

**Comment by rraallvv** [comment]
Maybe the AI could rate how clickbaity a title is, display the score on the thumbnail, and generate a new title based on the script or even by "watching" the video. This might have sounded like science fiction two or three years ago, but now it doesn't seem far-fetched.

**Comment by aspizu** [comment]
```py
import os

from dotenv import load_dotenv
from google import genai
from youtube_transcript_api import YouTubeTranscriptApi

load_dotenv()

client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))

video_id = "xy-u1evNmVo"
transcript = YouTubeTranscriptApi.get_transcript(video_id)
transcript_text = " ".join([entry["text"] for entry in transcript])

PROMPT = """
Titles are supposed to give you a good description of what's going to happen in the video. 
Prefer a descriptive subject or a ... (entirety of the de arrow guidelines)

Generate a single video title from the following transcript of a YouTube video.

Transcript:
{transcript}
"""

response = client.models.generate_content(
    model="gemini-2.0-flash",
    contents=PROMPT.format(transcript=transcript_text),
)

print(response.text)
```
