### ISSUE TITLE
Feature Request] Option to show only the modified title and thumbnail on hover. When not hovering, revert them to the original

### ISSUE THREAD

**Issue by pota2dev** [ajayyy/DeArrow#318]
I need an option to show only the modified title and thumbnail when hovering mouse on video, instead of clicking a button. When not hovering, revert them to the original.

Or there could be an option to toggle between original and modified title+thumbnail on hover. 

![image](https://github.com/user-attachments/assets/f10d6e8c-fefd-4b41-a03e-bb84491b7917)

**Comment by ajayyy** [comment]
#278

**Comment by pota2dev** [comment]
@ajayyy Actually the title is what I'm concerned of. And I've kept the Thumbnail disabled. The issue that you referred to are only about thumbnail. 

You can implement an option to toggle between the original and modified title on hover. I think, it won't disable "YouTube's hover play" feature.
