### ISSUE TITLE
What type of data will the extension collect overall?

### ISSUE THREAD

**Issue by meetzaveri** [ajayyy/DeArrow#42]
Loved the product after coming across it on HN. Before dangling my feet into, I would like to ask what type of data does extension collect on our behalf? 

Assuming it engages with the videos/feeds by YT, that means it will process lots of videos and will manipulate browser state to show us non-clickbait-ish title. What will be the avg. consumption of CPU by this extension's backend code ?

Thanks!

**Comment by ajayyy** [comment]
See https://gist.github.com/ajayyy/9bfec83d57ea34f5182658ec8445aa9d and https://dearrow.ajay.app/about
