### ISSUE TITLE
m.youtube.com support

### ISSUE THREAD

**Issue by clonejo** [ajayyy/DeArrow#44]
Tried DeArrow v1.0.10 from AMO with both Firefox 114.0.2 on Fedora and Firefox 115.0b4 on Android. I tried on Android first, but found it can easily be reproduced on desktop with the Responsive Design Mode (just watch out you don't keep `?app=desktop` in the URL).

Screenshots and video titles just stay original. By the way SponsorBlock works just fine in these scenarios.

**Comment by ajayyy** [comment]
Yes, it is not supported at the moment

**Comment by synthead** [comment]
I am very interested in using this with Firefox for Android!

**Comment by ajayyy** [comment]
Should be done later this week

**Comment by ajayyy** [comment]
Will comment when published

**Comment by ajayyy** [comment]
Published

**Comment by ajayyy** [comment]
After deploying I noticed some bugs.... But at least there's initial support. Will work on fixing those for the next version

**Comment by clonejo** [comment]
Thank you so much! Gonna recommend DeArrow to some more people.
