### ISSUE TITLE
Compatibility with Enhancer for YouTube™

### ISSUE THREAD

**Issue by PhantomGamers** [ajayyy/DeArrow#53]
When DeArrow is enabled on my Firefox browser, [Enhancer for Youtube](https://www.mrfdev.com/enhancer-for-youtube) stops functioning altogether.

I suppose this is probably related to #52 but I'm not certain.

**Comment by matjarosz** [comment]
Intrestingly Enhancer does work with DeArrow on my end, but it does remove the ability to create my own title submissions. 

Using Firefox 114.0.2 on MacOS Ventura

**Comment by ajayyy** [comment]
I don't see any issues with enhancer anymore on my end. Maybe this was fixed in 1.1.0?

**Comment by PhantomGamers** [comment]
Yup, seems fixed now! Thanks :)

**Comment by matjarosz** [comment]
Likewise, the edit button is also working. Thanks for getting this one resolved!

**Comment by scmanjarrez** [comment]
Not working for me, I'm using version 1.6.4 of DeArrow and 2.0.126 of Enhancer for Youtube. The panel of Enhancer for Youtube is hidden when DeArrow is enabled.
