### ISSUE TITLE
'This Content isn't available' message replacing Thumbnails

### ISSUE THREAD

**Issue by Siveen** [ajayyy/DeArrow#54]
![image](https://github.com/ajayyy/DeArrow/assets/59781998/8f30e28f-9bf1-4e08-9eb6-cfa09eace7ad)
It doesn't seem to happen to happen with every Video (as shown in the screenshot). I haven't quite identified what links these videos together - time period doesn't seem to be a factor (the video in the bottom left was posted 7 years ago, while the other two videos are recent posts).
Possibly a Browser-exclusive issue? I am using Vivaldi and the Chrome-rated Extension.

**Comment by ajayyy** [comment]
Related https://github.com/iv-org/invidious/issues/3915

**Comment by ajayyy** [comment]
Using a proxy service now and it seems to be good. Also added detection now for when YouTube gives the wrong video details, so it should just resort to local thumbnail generation instead if IPs are blocked in the future.
