### ISSUE TITLE
[Feature] Option to exclude all videos on the subscriptions page

### ISSUE THREAD

**Issue by cyberworm** [ajayyy/DeArrow#56]
Hi,

I'd like to disable the replacement on all the videos that are shown on my subscription page. I don't think subscribed channels are the proper target for this extension. I suppose simply excluding the videos on the subscription page won't be enough, since the replacement would still happen on the actual videos.

I could work around that by adding every single subscribed channel to the Channel Allowlist, but that requires quite some maintenance effort.

**Comment by ajayyy** [comment]
#45
