### ISSUE TITLE
Option to show original titles/thumbnails by default

### ISSUE THREAD

**Issue by GrantGryczan** [ajayyy/DeArrow#57]
Currently the extension is unusable for me because I find myself tediously checking every single video's original title to see what it was. This made me realize I'd rather see that by default.

I'd much rather see the title the original uploader intended, and only view the alternative one if I feel I have a problem with the original not being clear enough (which is only occasionally the case for me).

**Comment by GrantGryczan** [comment]
> If you toggle the enabled slider, you will get this behavior. It still has the "show custom" button on hover.

I'm not seeing this. I switched the "Enabled" slider to say "Disabled" in the extension's pop-up, and I no longer see any button on hover on my Home page.

**Comment by ajayyy** [comment]
![image](https://github.com/ajayyy/DeArrow/assets/12688112/88d36b8f-6400-4d95-a1b5-1e75a10492f3)

For me it does behave like this.

**Comment by ajayyy** [comment]
![image](https://github.com/ajayyy/DeArrow/assets/12688112/37075e2a-97ce-4e24-a89f-3923aeb576e7)

To be specific, I'm talking about this toggle

**Comment by GrantGryczan** [comment]
I updated and now I see it! Though I'd argue that toggle should just be an option for whether to default to original titles, rather than labeling itself as enabling or disabling the extension entirely. That would be clearer :)

**Comment by ajayyy** [comment]
Good point, maybe it can just "show original" when toggled off

**Comment by GrantGryczan** [comment]
I think it'd be clearer if you said it were _defaulting_ to original. But also, even if you did change the text for "Disabled", you'd never know about it unless you tried it, so I do think it would be better as just a normal option instead of "Enabled" which is more ambiguous.

**Comment by ajayyy** [comment]
![image](https://github.com/ajayyy/DeArrow/assets/12688112/f84208c2-27ab-48e8-b5ad-a2b0af3baa1a)

Added a dedicated setting. Changed behavior of enabled to be more straight-forward.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/DeArrow/commit/ed78a02faa9e794ca6f98aa512c22e2a7aec8265

**Comment by GrantGryczan** [comment]
Excellent. Thank you!
