### ISSUE TITLE
Fonts issue

### ISSUE THREAD

**Issue by OleksanderSalamatov** [ajayyy/DeArrow#60]
Some fonts after transformation show ? symbols instead of letters 
![image](https://github.com/ajayyy/DeArrow/assets/84843611/0e416b2a-9f4d-422e-ad03-a8aff8e39301)
![image](https://github.com/ajayyy/DeArrow/assets/84843611/a930ab8b-59bd-4524-8301-7aad9ef039b2)

**Comment by ajayyy** [comment]
Hmm, this also should probably be converted to normal text anyway

**Comment by SuperStormer** [comment]
Fixed by #76
