### ISSUE TITLE
Old auto-generated thumbnails sometimes displayed after it has changed

### ISSUE THREAD

**Issue by sapphyrus** [ajayyy/DeArrow#61]
Sometimes the auto-generated thumbnails end up being images of sponsored segments, like here: 

![Image](https://i.imgur.com/bG3SWLK.png)

These can be manually fixed / better thumbnails can be crowdsourced, but I think integrating DeArrow with your other project, SponsorBlock, would be a no-brainer. Ignoring intros / outtros would be good too.

**Comment by ajayyy** [comment]
This is already the case, it seems to be some caching bug that caused the thumbnail generated before a sponsorblock submitted to be shown for some reason. Will investigate closer next time I notice it.

**Comment by ajayyy** [comment]
Found the issue
