### ISSUE TITLE
Delay/Lag when Closing/Switching a YT Tab.

### ISSUE THREAD

**Issue by CharAznableLoNZ** [ajayyy/DeArrow#62]
I like the project and switched to this from "clickbait remover for youtube". 

I open several video tabs at once on my HTPC and then close each tab once the video ends and click the next tab.  I have noticed that after closing that tab, the browser hangs for a few seconds.  When I disabled DeArrow the issue stops.  I'm not sure if the hang is on closing that tab or loading the just clicked tab.

The only default option I have changed is antialiased thumbnails since I don't care about jagged lines on a thumbnail and suspected that could be the cause of the delay. 
 
My HTPC is an M93p Tiny with a 4570T, it's not a powerhouse but more than enough for some YT videos on a 1080 TV.

I use FF 114.0.2 on W10 22H2
The extension version is 1.0.10

**Comment by ajayyy** [comment]
Next version uses img elements instead of canvas which should fix this

**Comment by ajayyy** [comment]
Fixed in 1.1.0
