### ISSUE TITLE
Cannot insert ">" (Greater than) character in titles

### ISSUE THREAD

**Issue by RustyNova016** [ajayyy/DeArrow#63]
I've come over a particular edge case on a video where the author discuss about `&Option<T> `and `Option<&T>` from Rust: 
https://www.youtube.com/watch?v=6c7pZYP_iIE

The original title is "Choose the right option" which can be misinterpreted for being a philosophical or casual video instead of a programming one. And more, the video itself is biased toward Option<&T>. So I thought that "Prefer using Option<&T> over &Option<T>" is a better title for it.

However, the ">" character isn't showing up, and I think this should be fixed, or try to add an escape character to prevent html insertion

**Comment by ajayyy** [comment]
We actually use greater than as a special character indicating that a word should not be have its formatting changed (`>word`). We chose this because YouTube official titles can't have greater than sign either.

It should be more clear in the UI though.

**Comment by DivineWinds** [comment]
Using [confusable characters](https://util.unicode.org/UnicodeJsps/confusables.jsp?a=%3C%3E&r=None) like ˂˃ (U+02C2, U+02C3) is always an option. They are even allowed in official titles.

**Comment by ajayyy** [comment]
Another option would be to allow `\>`. Still would need a better way to indicate that to the submitter.

**Comment by DivineWinds** [comment]
To be fair anything would be better than the current situation where the extension effectively lifts the restriction YT placed on angle brackets... but only for the left one.

**Comment by DivineWinds** [comment]
> Another option would be to allow `\>`, which would become `>`. Still would need a better way to indicate that to the submitter.

Just make sure we will be able to use literal `\>` in titles without needing zero-width spaces or something.

**Comment by ajayyy** [comment]
Right now `>` is only used at the start of a word, so another option is allowing it everywhere else. Would `>` at the start of the word be useful anywhere?

**Comment by DivineWinds** [comment]
> Right now `>` is only used at the start of a word, so another option is allowing it everywhere else. Would `>` at the start of the word be useful anywhere?

Maybe on a video about greentext?

**Comment by ajayyy** [comment]
Went with the last solution for not
