### ISSUE TITLE
Allow Voting for the Original Title

### ISSUE THREAD

**Issue by MaximilianEmel** [ajayyy/DeArrow#66]
There should be an option to vote for the original title.

**Comment by ajayyy** [comment]
You can, it appears in the box and it stores that it is an original title.

**Comment by ajayyy** [comment]
Or are you referring to those auto updating titles?

**Comment by MaximilianEmel** [comment]
Oh I didn't even realize it was, since the title I saw had changed.

**Comment by MaximilianEmel** [comment]
I actually think it would be a bad idea to support auto-updating ones.

**Comment by ajayyy** [comment]
Yea, now that I think of it they probably should have more descriptive titles anyway

**Comment by MaximilianEmel** [comment]
Well I think there's nothing wrong with using the original title, just that if it is decided that the original is acceptable, it should certainly be locked in at whatever it was at the time.
