### ISSUE TITLE
Pencil icon only shows up after visiting a channel page

### ISSUE THREAD

**Issue by kroltan** [ajayyy/DeArrow#69]
I was trying to add a submission for a video, but the pencil icon does not appear next to the title.

![2023-07-02_12-06](https://github.com/ajayyy/DeArrow/assets/978042/8f86bad1-a4b7-49e3-82f7-bf817e5c0e66)

I do use a lot of addons that modify the Youtube website, but I tried disabling all addons except DeArrow and opening the video on a brand new tab, but it still doesn't show up.

What does make it show up is going to any channel channel page, then going back to the video I was actually watching. Then that tab works fine, I can go watch more videos, go back to the home, whatever. But at some point I haven't figured out, it disappears again.

**Comment by ajayyy** [comment]
Fixed in 1.1.0
