### ISSUE TITLE
Submitted title shows up on different videos clicked

### ISSUE THREAD

**Issue by raashnachand** [ajayyy/DeArrow#70]
Steps to recreate:
1. Submit a title and thumbnail for a video as normal
2. Click on another video to watch
3. The title submitted for the previous video is now displayed for the video just clicked.

**Comment by Caffeineix** [comment]
Having this issue on Firefox.

**Comment by wizpizz** [comment]
> Having this issue on Firefox.

Happens on Google Chrome as well. I don't think it's browser related.

**Comment by ajayyy** [comment]
Is this still occuring?

**Comment by raashnachand** [comment]
> Is this still occuring?

Doesn't appear to anymore on my end.
