### ISSUE TITLE
Add a setting to hide the "small" Dearrow button on hover

### ISSUE THREAD

**Issue by Maruhai** [ajayyy/DeArrow#71]
These are for videos that have automatically modified name and thumbnails, I will almost never care about seeing the default ones for them. Side effect, this effectively removes the ability to check their original versions.

**Comment by ajayyy** [comment]
What do you mean by hide on hover?

**Comment by ajayyy** [comment]
Like never show it?

**Comment by ajayyy** [comment]
c5473e50fa1fd242d3acc629a4715efba5420701
