### ISSUE TITLE
Downvotes

### ISSUE THREAD

**Issue by sebm253** [ajayyy/DeArrow#74]
This would be really helpful when a VIP, for example, notices a bad title/thumbnail but doesn't want to make their own submission or lock the original.

**Comment by Blue-Sauce** [comment]
I guess VIP status would be those who have a much higher number of upvotes than average on their submissions?

**Comment by mlnrDev** [comment]
> I guess VIP status would be those who have a much higher number of upvotes than average on their submissions?

https://wiki.sponsor.ajay.app/w/FAQ#Are_there_any_moderators%3F
