### ISSUE TITLE
auto convert certain Unicode Latin characters to the ASCII equivalents

### ISSUE THREAD

**Issue by SuperStormer** [ajayyy/DeArrow#78]
For example, all of the bold, italics, etc, letters here https://www.compart.com/en/unicode/block/U+1D400 which are sometimes used instead of ASCII letters in YT titles to make it look fancy or something. I have personally never seen any of them used for any legitimate purpose in a title.

Current list of applicable characters:
- ["Mathematical Alphanumeric Symbols"](https://www.compart.com/en/unicode/block/U+1D400)
- [fullwidth characters](https://en.wikipedia.org/wiki/Halfwidth_and_Fullwidth_Forms_(Unicode_block))
- [letter emojis](https://en.wikipedia.org/wiki/Enclosed_Alphanumeric_Supplement)
- [small caps](https://en.wikipedia.org/wiki/Small_caps#IPA_symbol_set)

**Comment by ajayyy** [comment]
I have a feeling chat gpt could be useful to get a list of character maps

**Comment by mchangrh** [comment]
should this also be used for replacing 🅱️, α Α (Alpha) and similar glyphs that aren't transformation of a letter but are commonly used as replacements?

**Comment by ajayyy** [comment]
ooh, interesting. The new emoji cleaning probably broke a lot of 🅱️ titles

**Comment by ajayyy** [comment]
![Screenshot_20230720-125800_Firefox_Nightly](https://github.com/ajayyy/DeArrow/assets/12688112/9938b0b5-e86b-46df-b19f-de3dba1eef29)

Yea...

**Comment by ajayyy** [comment]
I think we should exclude letter emojis until this issue is complete

**Comment by mchangrh** [comment]
We might have to add exclusions for B, A and AB since they are in the pictograph range iirc

**Comment by ajayyy** [comment]
Added

**Comment by SuperStormer** [comment]
A partial solution would be [NFKC normalization](https://www.unicode.org/glossary/#normalization_form_kc).

list of character replacements: [out.txt](https://github.com/ajayyy/DeArrow/files/13958583/out.txt)
```py
import sys
import unicodedata
from pprint import pprint

chrs = [chr(c) for c in range(sys.maxunicode+1)]
pprint([(c,unicodedata.normalize("NFKC",c),unicodedata.name(c,None),unicodedata.name(unicodedata.normalize('NFKC',c)[0],None)) for c in chrs if unicodedata.normalize('NFKC', c)!=c])
```

Note that this doesn't fix letter emojis, nor small caps.

**Comment by mchangrh** [comment]
I've used NFKD and NFKC normalization in other projects before, It creates a mess out of emojis. I prefer https://github.com/gc/confusables for normalization using a map

**Comment by ajayyy** [comment]
> There's a JS function to normalize strings and one of the modes should work well for this ("𝗠𝘆 𝗖𝗼𝗼𝗹 𝗧𝗶𝘁𝗹𝗲".normalize("NFKD") results in "My Cool Title")

https://github.com/ajayyy/DeArrow/issues/283
