### ISSUE TITLE
Label under video player showing old or original title after voting on title

### ISSUE THREAD

**Issue by ElectronicRU** [ajayyy/DeArrow#80]
I didn't like the title first displayed (A), so I voted for a different title (B). It seemed to refresh, but was still showing title A. I tried again - it started showing the original title, while the "Show original" button was still blue. After flicking the button on and off, it went back to the title A.

I tried editing and submitting my own titles before, and it was updating the title on the page under the player as well, so I assume that's the intended behaviour.

**Comment by ajayyy** [comment]
I believe this is fixed
