### ISSUE TITLE
Option in Allowlist to show DeArrow title/thumbnail by default

### ISSUE THREAD

**Issue by aleksejrs** [ajayyy/DeArrow#82]
#57 / https://github.com/ajayyy/DeArrow/commit/ed78a02faa9e794ca6f98aa512c22e2a7aec8265 made it possible to disable replacing by default, but there is no way to re-enable that for particular channels.

**Comment by megat69** [comment]
Bump.

I came here to ask for that feature.
There are particular channels I would love this to be enabled by default, while not making it the norm.

**Comment by ajayyy** [comment]
@megat69 use 👍 reaction so I can more easily sort issues
