### ISSUE TITLE
Add ability to vote for the original title/thumbnail to confirm that it's not clickbait

### ISSUE THREAD

**Issue by RubenKelevra** [ajayyy/DeArrow#89]
I've noticed that there's currently no ability to vote for the original title/thumbnail. That's weird, as most thumbnails/titles are not clickbait and shouldn't need to be overridden. But I don't see how I can submit this information.

Which means that these videos will never show a thumbnail if you select "show empty box" if there's no other submission available.

I think it should be possible to do acceptance voting (multiple choice what's acceptable to the user) on all submissions, including the submission by the author of the video.

If the acceptance is lower than 50% for the original thumbnail/title, the one with the highest acceptance voting of the other submissions should be shown.

This would help to avoid "spam" submissions from showing up, as the original title/thumbnail would only be discarded, if it's not acceptable for most users.

**Comment by RubenKelevra** [comment]
Two buttons with "this is clickbait/this title is acceptable" next to the title would maybe help to get more engagement without having the users to come up with new ideas on the spot.

After clicking, the voting would be submitted and the user can up/down vote the titles in the box on the right.

Down vote would just add a voting count, while up vote marks it as "acceptable". So different voting amounts for different titles/thumbnails can be compared, just by the percent of acceptance, with a threshold like 10 votes minimum to be rated.

**Comment by ajayyy** [comment]
> most thumbnails/titles are not clickbait and shouldn't need to be overridden.

You seem to have a different usecase of the extension, which is fine, but that is not how we are defining clickbait
