### ISSUE TITLE
Acronyms like NASA get de-capitalized with any option but 'Disabled'

### ISSUE THREAD

**Issue by earlt612** [ajayyy/DeArrow#96]

**Comment by ajayyy** [comment]
Right now it only lets 3 letters or fewer that don't have dots between letters, but NASA is 4. 

Not sure if that should be raised, or if NASA should be whitelisted

**Comment by ajayyy** [comment]
For submissions, you can fix captilization issues by adding a `>`

For example

> Visiting >NASA headquarters

**Comment by earlt612** [comment]
There could be a word whitelist where words on this list would be always capitalized.

**Comment by ajayyy** [comment]
If anyone wants to suggest more, please ask on discord or matrix for access to the Google Sheet.
