### ISSUE TITLE
Video freezing soon after playback start

### ISSUE THREAD

**Issue by DrymarchonShaun** [ajayyy/DeArrow#97]
A few seconds after starting playback, video will freeze, and only unfreeze after pausing and unpausing, or skipping back a few seconds, and then playback works fine until a new video is opened. 

Audio continues playing for a few seconds after the video freezes, eventually stopping and buffering endlessly.

Had this happen on firefox in both Arch Linux and NixOS. Unfamiliar with troubleshooting extensions, so I don't know what other information would be helpful.

**Comment by ajayyy** [comment]
I have noticed this recently, so maybe some newer change

**Comment by DrymarchonShaun** [comment]
Anecdotally related, but I figured I'd mention it anyway in case it is in fact related -

I noticed my system running a bit hotter than usual as well. At one point checking cpu usage to see if I could figure out the cause, Firefox had a single core pegged at 100%, staying that way for a good 20+ minutes until I closed and re-opened Firefox.

_Very likely to be unrelated; I've been majorly reworking my system configuration recently (been back and forth between arch and nixos over the past few days.)_

**Comment by nerivera** [comment]
I'm experiencing the same video freezing issue with macOS Ventura 13.4.1 (c), Firefox 115.0.2 (64-bit), and DeArrow 1.1.5. I don't know whether my CPU usage is higher than usual; I can only confirm the video freezing exactly as described in this issue.

**Comment by jroneilky** [comment]
Happening to me too. Firefox on Arch.
