### ISSUE TITLE
521 errors on every thumbnail request, slowing down YouTube

### ISSUE THREAD

**Issue by iGerman00** [ajayyy/DeArrow#99]
![msedge (2023-07-13 15։08։44)](https://github.com/ajayyy/DeArrow/assets/36676880/34875f5e-c6f8-4883-b326-285740bc8b32)
Googling around the 521 error status code, it seems to be Cloudflare-related. I am not really banned on any other sites but my IP is static and shared with around 300 other people (apartment internet). Opening any [URL](https://dearrow-thumb.ajay.app/api/v1/getThumbnail?videoID=H5e3ALqgpaA&officialTime=false&generateNow=false) in the browser loads fine.

**Comment by ajayyy** [comment]
The server died. Seems the cache eviction broke again, so will have to look into that.

**Comment by ajayyy** [comment]
Added to https://status.sponsor.ajay.app/
